# Generated by Django 4.2 on 2023-04-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_rename_user_orderfile_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='color',
            field=models.CharField(max_length=255, null=True, verbose_name='Цвет (negative - красный, success - зеленый, info - синий, warning - желтый)'),
        ),
        migrations.AddField(
            model_name='paystatus',
            name='color',
            field=models.CharField(max_length=255, null=True, verbose_name='Цвет (negative - красный, success - зеленый, info - синий, warning - желтый)'),
        ),
    ]
