# Generated by Django 4.2 on 2023-05-04 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_orderstatus_color_alter_paystatus_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfile',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='data.order')),
            ],
        ),
    ]
