# Generated by Django 4.2.2 on 2023-06-21 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0008_orderfile_created_at_ordercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направление',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статус заказа'},
        ),
        migrations.AlterModelOptions(
            name='paystatus',
            options={'verbose_name': 'Статус оплаты', 'verbose_name_plural': 'Статус оплаты'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуга'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(null=True, upload_to='category/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='price_from',
            field=models.IntegerField(null=True, verbose_name='Цена от'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.FileField(null=True, upload_to='service/', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.FileField(null=True, upload_to='category/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='service',
            name='info_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст описания'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='service',
            name='work_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Срок исполнения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('flag', models.FileField(null=True, upload_to='flags/', verbose_name='Флаг')),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='data.direction')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страна',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.country'),
        ),
        migrations.AddField(
            model_name='service',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='data.direction'),
        ),
    ]
