# Generated by Django 4.2.2 on 2023-06-21 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_direction_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='direction',
        ),
        migrations.AddField(
            model_name='service',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_services', to='data.country'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_services', to='data.category'),
        ),
    ]
