# Generated by Django 4.2.2 on 2023-06-22 09:32

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_remove_service_direction_service_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='warn_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст предупреждения'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='data.category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='data.country'),
        ),
        migrations.CreateModel(
            name='ServiceTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержимое таба')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='data.service')),
            ],
            options={
                'verbose_name': 'Таб',
                'verbose_name_plural': 'Таб',
            },
        ),
    ]
