# Generated by Django 4.2.2 on 2023-06-22 09:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_service_warn_text_alter_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='info_tab',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержимое информационного таба'),
        ),
    ]
