# Generated by Django 4.2.2 on 2023-07-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_service_info_tab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='country',
        ),
        migrations.AddField(
            model_name='service',
            name='countries',
            field=models.ManyToManyField(to='data.country'),
        ),
    ]
