# Generated by Django 4.2.2 on 2023-07-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_remove_service_country_service_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='banner/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннер',
            },
        ),
    ]
