# Generated by Django 4.2.2 on 2023-08-27 17:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_alter_callbackform_comment_alter_callbackform_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='service/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='category/', verbose_name='Картинка'),
        ),
    ]
