# Generated by Django 4.2.2 on 2023-08-31 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_country_text_alter_service_icon_alter_service_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callbackform',
            options={'ordering': ('-created_at',)},
        ),
    ]
