# Generated by Django 4.2.2 on 2023-09-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_alter_callbackform_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackform',
            name='is_hidden',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
