# Generated by Django 4.2 on 2023-04-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Почта'),
        ),
    ]
