# Generated by Django 4.2 on 2023-04-27 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usernetworks_remove_usernetwork_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernetwork',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usernetworks'),
        ),
    ]
