# Generated by Django 4.2.2 on 2023-08-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_usercomment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='ava/'),
        ),
    ]
